Started
.ElementFinder {
  browser_:
   ProtractorBrowser {
     controlFlow: [Function],
     schedule: [Function],
     setFileDetector: [Function],
     getExecutor: [Function],
     getSession: [Function],
     getCapabilities: [Function],
     quit: [Function],
     actions: [Function],
     touchActions: [Function],
     executeScript: [Function],
     executeAsyncScript: [Function],
     call: [Function],
     wait: [Function],
     sleep: [Function],
     getWindowHandle: [Function],
     getAllWindowHandles: [Function],
     getPageSource: [Function],
     close: [Function],
     getCurrentUrl: [Function],
     getTitle: [Function],
     findElementInternal_: [Function],
     findElementsInternal_: [Function],
     takeScreenshot: [Function],
     manage: [Function],
     switchTo: [Function],
     driver:
      thenableWebDriverProxy {
        flow_: [Object],
        session_: [Object],
        executor_: [Object],
        fileDetector_: null,
        onQuit_: undefined,
        cancel: [Function],
        then: [Function: bound then],
        catch: [Function: bound then],
        getNetworkConnection: [Function],
        setNetworkConnection: [Function],
        toggleAirplaneMode: [Function],
        toggleWiFi: [Function],
        toggleData: [Function],
        toggleLocationServices: [Function],
        getGeolocation: [Function],
        setGeolocation: [Function],
        getCurrentDeviceActivity: [Function],
        startDeviceActivity: [Function],
        getAppiumSettings: [Function],
        setAppiumSettings: [Function],
        getCurrentContext: [Function],
        selectContext: [Function],
        getScreenOrientation: [Function],
        setScreenOrientation: [Function],
        isDeviceLocked: [Function],
        lockDevice: [Function],
        unlockDevice: [Function],
        installApp: [Function],
        isAppInstalled: [Function],
        removeApp: [Function],
        pullFileFromDevice: [Function],
        pullFolderFromDevice: [Function],
        pushFileToDevice: [Function],
        listContexts: [Function],
        uploadFile: [Function],
        switchToParentFrame: [Function],
        fullscreen: [Function],
        sendAppToBackground: [Function],
        closeApp: [Function],
        getAppStrings: [Function],
        launchSession: [Function],
        resetApp: [Function],
        hideSoftKeyboard: [Function],
        getDeviceTime: [Function],
        openDeviceNotifications: [Function],
        rotationGesture: [Function],
        shakeDevice: [Function],
        sendChromiumCommand: [Function],
        sendChromiumCommandAndGetResult: [Function] },
     element: { [Function: element] all: [Function] },
     '$': [Function],
     '$$': [Function],
     baseUrl: '',
     getPageTimeout: 10000,
     params: {},
     resetUrl: 'data:text/html,<html></html>',
     debugHelper: DebugHelper { browserUnderDebug_: [Circular] },
     ready:
      ManagedPromise {
        flow_: [Object],
        stack_: null,
        parent_: null,
        callbacks_: null,
        state_: 'fulfilled',
        handled_: true,
        value_: [Circular],
        queue_: null },
     trackOutstandingTimeouts_: true,
     mockModules_: [ [Object] ],
     ExpectedConditions: ProtractorExpectedConditions { browser: [Circular] },
     plugins_:
      Plugins {
        setup: [Function],
        onPrepare: [Function],
        teardown: [Function],
        postResults: [Function],
        postTest: [Function],
        onPageLoad: [Function],
        onPageStable: [Function],
        waitForPromise: [Function],
        waitForCondition: [Function],
        pluginObjs: [],
        assertions: {},
        resultsReported: false },
     allScriptsTimeout: 11000,
     getProcessedConfig: [Function],
     forkNewDriverInstance: [Function],
     restart: [Function],
     restartSync: [Function],
     internalRootEl: '',
     internalIgnoreSynchronization: false },
  then: [Function],
  parentElementArrayFinder:
   ElementArrayFinder {
     browser_:
      ProtractorBrowser {
        controlFlow: [Function],
        schedule: [Function],
        setFileDetector: [Function],
        getExecutor: [Function],
        getSession: [Function],
        getCapabilities: [Function],
        quit: [Function],
        actions: [Function],
        touchActions: [Function],
        executeScript: [Function],
        executeAsyncScript: [Function],
        call: [Function],
        wait: [Function],
        sleep: [Function],
        getWindowHandle: [Function],
        getAllWindowHandles: [Function],
        getPageSource: [Function],
        close: [Function],
        getCurrentUrl: [Function],
        getTitle: [Function],
        findElementInternal_: [Function],
        findElementsInternal_: [Function],
        takeScreenshot: [Function],
        manage: [Function],
        switchTo: [Function],
        driver: [Object],
        element: [Object],
        '$': [Function],
        '$$': [Function],
        baseUrl: '',
        getPageTimeout: 10000,
        params: {},
        resetUrl: 'data:text/html,<html></html>',
        debugHelper: [Object],
        ready: [Object],
        trackOutstandingTimeouts_: true,
        mockModules_: [Array],
        ExpectedConditions: [Object],
        plugins_: [Object],
        allScriptsTimeout: 11000,
        getProcessedConfig: [Function],
        forkNewDriverInstance: [Function],
        restart: [Function],
        restartSync: [Function],
        internalRootEl: '',
        internalIgnoreSynchronization: false },
     getWebElements: [Function: getWebElements],
     locator_:
      { findElementsOverride: [Function: findElementsOverride],
        toString: [Function: toString] },
     actionResults_:
      ManagedPromise {
        flow_: [Object],
        stack_: null,
        parent_: [Object],
        callbacks_: null,
        state_: 'pending',
        handled_: false,
        value_: undefined,
        queue_: null },
     click: [Function],
     sendKeys: [Function],
     getTagName: [Function],
     getCssValue: [Function],
     getAttribute: [Function],
     getText: [Function],
     getSize: [Function],
     getLocation: [Function],
     isEnabled: [Function],
     isSelected: [Function],
     submit: [Function],
     clear: [Function],
     isDisplayed: [Function],
     getId: [Function],
     takeScreenshot: [Function] },
  elementArrayFinder_:
   ElementArrayFinder {
     browser_:
      ProtractorBrowser {
        controlFlow: [Function],
        schedule: [Function],
        setFileDetector: [Function],
        getExecutor: [Function],
        getSession: [Function],
        getCapabilities: [Function],
        quit: [Function],
        actions: [Function],
        touchActions: [Function],
        executeScript: [Function],
        executeAsyncScript: [Function],
        call: [Function],
        wait: [Function],
        sleep: [Function],
        getWindowHandle: [Function],
        getAllWindowHandles: [Function],
        getPageSource: [Function],
        close: [Function],
        getCurrentUrl: [Function],
        getTitle: [Function],
        findElementInternal_: [Function],
        findElementsInternal_: [Function],
        takeScreenshot: [Function],
        manage: [Function],
        switchTo: [Function],
        driver: [Object],
        element: [Object],
        '$': [Function],
        '$$': [Function],
        baseUrl: '',
        getPageTimeout: 10000,
        params: {},
        resetUrl: 'data:text/html,<html></html>',
        debugHelper: [Object],
        ready: [Object],
        trackOutstandingTimeouts_: true,
        mockModules_: [Array],
        ExpectedConditions: [Object],
        plugins_: [Object],
        allScriptsTimeout: 11000,
        getProcessedConfig: [Function],
        forkNewDriverInstance: [Function],
        restart: [Function],
        restartSync: [Function],
        internalRootEl: '',
        internalIgnoreSynchronization: false },
     getWebElements: [Function: getWebElements],
     locator_:
      { findElementsOverride: [Function: findElementsOverride],
        toString: [Function: toString] },
     actionResults_:
      ManagedPromise {
        flow_: [Object],
        stack_: null,
        parent_: [Object],
        callbacks_: null,
        state_: 'pending',
        handled_: false,
        value_: undefined,
        queue_: null },
     click: [Function],
     sendKeys: [Function],
     getTagName: [Function],
     getCssValue: [Function],
     getAttribute: [Function],
     getText: [Function],
     getSize: [Function],
     getLocation: [Function],
     isEnabled: [Function],
     isSelected: [Function],
     submit: [Function],
     clear: [Function],
     isDisplayed: [Function],
     getId: [Function],
     takeScreenshot: [Function] },
  click: [Function],
  sendKeys: [Function],
  getTagName: [Function],
  getCssValue: [Function],
  getAttribute: [Function],
  getText: [Function],
  getSize: [Function],
  getLocation: [Function],
  isEnabled: [Function],
  isSelected: [Function],
  submit: [Function],
  clear: [Function],
  isDisplayed: [Function],
  getId: [Function],
  takeScreenshot: [Function] }
ElementFinder {
  browser_:
   ProtractorBrowser {
     controlFlow: [Function],
     schedule: [Function],
     setFileDetector: [Function],
     getExecutor: [Function],
     getSession: [Function],
     getCapabilities: [Function],
     quit: [Function],
     actions: [Function],
     touchActions: [Function],
     executeScript: [Function],
     executeAsyncScript: [Function],
     call: [Function],
     wait: [Function],
     sleep: [Function],
     getWindowHandle: [Function],
     getAllWindowHandles: [Function],
     getPageSource: [Function],
     close: [Function],
     getCurrentUrl: [Function],
     getTitle: [Function],
     findElementInternal_: [Function],
     findElementsInternal_: [Function],
     takeScreenshot: [Function],
     manage: [Function],
     switchTo: [Function],
     driver:
      thenableWebDriverProxy {
        flow_: [Object],
        session_: [Object],
        executor_: [Object],
        fileDetector_: null,
        onQuit_: undefined,
        cancel: [Function],
        then: [Function: bound then],
        catch: [Function: bound then],
        getNetworkConnection: [Function],
        setNetworkConnection: [Function],
        toggleAirplaneMode: [Function],
        toggleWiFi: [Function],
        toggleData: [Function],
        toggleLocationServices: [Function],
        getGeolocation: [Function],
        setGeolocation: [Function],
        getCurrentDeviceActivity: [Function],
        startDeviceActivity: [Function],
        getAppiumSettings: [Function],
        setAppiumSettings: [Function],
        getCurrentContext: [Function],
        selectContext: [Function],
        getScreenOrientation: [Function],
        setScreenOrientation: [Function],
        isDeviceLocked: [Function],
        lockDevice: [Function],
        unlockDevice: [Function],
        installApp: [Function],
        isAppInstalled: [Function],
        removeApp: [Function],
        pullFileFromDevice: [Function],
        pullFolderFromDevice: [Function],
        pushFileToDevice: [Function],
        listContexts: [Function],
        uploadFile: [Function],
        switchToParentFrame: [Function],
        fullscreen: [Function],
        sendAppToBackground: [Function],
        closeApp: [Function],
        getAppStrings: [Function],
        launchSession: [Function],
        resetApp: [Function],
        hideSoftKeyboard: [Function],
        getDeviceTime: [Function],
        openDeviceNotifications: [Function],
        rotationGesture: [Function],
        shakeDevice: [Function],
        sendChromiumCommand: [Function],
        sendChromiumCommandAndGetResult: [Function] },
     element: { [Function: element] all: [Function] },
     '$': [Function],
     '$$': [Function],
     baseUrl: '',
     getPageTimeout: 10000,
     params: {},
     resetUrl: 'data:text/html,<html></html>',
     debugHelper: DebugHelper { browserUnderDebug_: [Circular] },
     ready:
      ManagedPromise {
        flow_: [Object],
        stack_: null,
        parent_: null,
        callbacks_: null,
        state_: 'fulfilled',
        handled_: true,
        value_: [Circular],
        queue_: null },
     trackOutstandingTimeouts_: true,
     mockModules_: [ [Object] ],
     ExpectedConditions: ProtractorExpectedConditions { browser: [Circular] },
     plugins_:
      Plugins {
        setup: [Function],
        onPrepare: [Function],
        teardown: [Function],
        postResults: [Function],
        postTest: [Function],
        onPageLoad: [Function],
        onPageStable: [Function],
        waitForPromise: [Function],
        waitForCondition: [Function],
        pluginObjs: [],
        assertions: {},
        resultsReported: false },
     allScriptsTimeout: 11000,
     getProcessedConfig: [Function],
     forkNewDriverInstance: [Function],
     restart: [Function],
     restartSync: [Function],
     internalRootEl: '',
     internalIgnoreSynchronization: false },
  then: [Function],
  parentElementArrayFinder:
   ElementArrayFinder {
     browser_:
      ProtractorBrowser {
        controlFlow: [Function],
        schedule: [Function],
        setFileDetector: [Function],
        getExecutor: [Function],
        getSession: [Function],
        getCapabilities: [Function],
        quit: [Function],
        actions: [Function],
        touchActions: [Function],
        executeScript: [Function],
        executeAsyncScript: [Function],
        call: [Function],
        wait: [Function],
        sleep: [Function],
        getWindowHandle: [Function],
        getAllWindowHandles: [Function],
        getPageSource: [Function],
        close: [Function],
        getCurrentUrl: [Function],
        getTitle: [Function],
        findElementInternal_: [Function],
        findElementsInternal_: [Function],
        takeScreenshot: [Function],
        manage: [Function],
        switchTo: [Function],
        driver: [Object],
        element: [Object],
        '$': [Function],
        '$$': [Function],
        baseUrl: '',
        getPageTimeout: 10000,
        params: {},
        resetUrl: 'data:text/html,<html></html>',
        debugHelper: [Object],
        ready: [Object],
        trackOutstandingTimeouts_: true,
        mockModules_: [Array],
        ExpectedConditions: [Object],
        plugins_: [Object],
        allScriptsTimeout: 11000,
        getProcessedConfig: [Function],
        forkNewDriverInstance: [Function],
        restart: [Function],
        restartSync: [Function],
        internalRootEl: '',
        internalIgnoreSynchronization: false },
     getWebElements: [Function: getWebElements],
     locator_:
      name(name) {
    return By.css('*[name="' + escapeCss(name) + '"]');
  } {
        using: 'xpath',
        value: 'html/body/div[2]/div[1]/div[2]/div[2]/div/h1' },
     actionResults_:
      ManagedPromise {
        flow_: [Object],
        stack_: null,
        parent_: [Object],
        callbacks_: null,
        state_: 'pending',
        handled_: false,
        value_: undefined,
        queue_: null },
     click: [Function],
     sendKeys: [Function],
     getTagName: [Function],
     getCssValue: [Function],
     getAttribute: [Function],
     getText: [Function],
     getSize: [Function],
     getLocation: [Function],
     isEnabled: [Function],
     isSelected: [Function],
     submit: [Function],
     clear: [Function],
     isDisplayed: [Function],
     getId: [Function],
     takeScreenshot: [Function] },
  elementArrayFinder_:
   ElementArrayFinder {
     browser_:
      ProtractorBrowser {
        controlFlow: [Function],
        schedule: [Function],
        setFileDetector: [Function],
        getExecutor: [Function],
        getSession: [Function],
        getCapabilities: [Function],
        quit: [Function],
        actions: [Function],
        touchActions: [Function],
        executeScript: [Function],
        executeAsyncScript: [Function],
        call: [Function],
        wait: [Function],
        sleep: [Function],
        getWindowHandle: [Function],
        getAllWindowHandles: [Function],
        getPageSource: [Function],
        close: [Function],
        getCurrentUrl: [Function],
        getTitle: [Function],
        findElementInternal_: [Function],
        findElementsInternal_: [Function],
        takeScreenshot: [Function],
        manage: [Function],
        switchTo: [Function],
        driver: [Object],
        element: [Object],
        '$': [Function],
        '$$': [Function],
        baseUrl: '',
        getPageTimeout: 10000,
        params: {},
        resetUrl: 'data:text/html,<html></html>',
        debugHelper: [Object],
        ready: [Object],
        trackOutstandingTimeouts_: true,
        mockModules_: [Array],
        ExpectedConditions: [Object],
        plugins_: [Object],
        allScriptsTimeout: 11000,
        getProcessedConfig: [Function],
        forkNewDriverInstance: [Function],
        restart: [Function],
        restartSync: [Function],
        internalRootEl: '',
        internalIgnoreSynchronization: false },
     getWebElements: [Function: getWebElements],
     locator_:
      name(name) {
    return By.css('*[name="' + escapeCss(name) + '"]');
  } {
        using: 'xpath',
        value: 'html/body/div[2]/div[1]/div[2]/div[2]/div/h1' },
     actionResults_:
      ManagedPromise {
        flow_: [Object],
        stack_: null,
        parent_: [Object],
        callbacks_: null,
        state_: 'pending',
        handled_: false,
        value_: undefined,
        queue_: null },
     click: [Function],
     sendKeys: [Function],
     getTagName: [Function],
     getCssValue: [Function],
     getAttribute: [Function],
     getText: [Function],
     getSize: [Function],
     getLocation: [Function],
     isEnabled: [Function],
     isSelected: [Function],
     submit: [Function],
     clear: [Function],
     isDisplayed: [Function],
     getId: [Function],
     takeScreenshot: [Function] },
  click: [Function],
  sendKeys: [Function],
  getTagName: [Function],
  getCssValue: [Function],
  getAttribute: [Function],
  getText: [Function],
  getSize: [Function],
  getLocation: [Function],
  isEnabled: [Function],
  isSelected: [Function],
  submit: [Function],
  clear: [Function],
  isDisplayed: [Function],
  getId: [Function],
  takeScreenshot: [Function] }
F

Failures:
1) angularjs homepage todo list added name
  Message:
    Expected 'Hello Tarun!' to equal 'Hello Tarun'.
  Stack:
    Error: Failed expectation
        at UserContext.<anonymous> (C:\Users\tjaiswal\Desktop\procatractor\firstProTest.js:24:20)
        at C:\Users\tjaiswal\AppData\Roaming\npm\node_modules\protractor\node_modules\jasminewd2\index.js:112:25
        at new ManagedPromise (C:\Users\tjaiswal\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:1077:7)
        at ControlFlow.promise (C:\Users\tjaiswal\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2505:12)
        at schedulerExecute (C:\Users\tjaiswal\AppData\Roaming\npm\node_modules\protractor\node_modules\jasminewd2\index.js:95:18)
        at TaskQueue.execute_ (C:\Users\tjaiswal\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:3084:14)
        at TaskQueue.executeNext_ (C:\Users\tjaiswal\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:3067:27)
        at asyncRun (C:\Users\tjaiswal\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2974:25)
        at C:\Users\tjaiswal\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:668:7